### ISSUE TITLE
New db setup

### ISSUE THREAD

**Issue by dgpaci** [genropy/genropy#40]

**Comment by cgabriel** [comment]
Closing this, no description provided and no commit referenced to the issue, assuming it's the feature/new-dbsetup branch which has been merged today into develop branch.

**Comment by dgpaci** [comment]
When a relation towards a table and same relation name already exists, an error is raised, but no more informations in provided

Es: relation_name='articoli' (table articolo) vs relation_name='articoli' (table prodotto).

It's obviously wrong, but it would be useful to tell the developer the relation name already exists instead of just raising the error...

**Comment by cgabriel** [comment]
I'm closing this issue and opening a specific one about the relation, since it's a different topic, and the original ticket was too obscure.
